version: '3'
services:
  db:
    image: mysql:8.0.22
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DOCKER_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DOCKER_MYSQL_DATABASE
      MYSQL_USER: $DOCKER_MYSQL_USER
      MYSQL_PASSWORD: $DOCKER_MYSQL_PASSWORD
    container_name: momophoto_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake

  api:
    volumes:
      - ./api:/go/src/api
    build: ./api
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      MYSQL_DB_HOST: $DOCKER_MYSQL_DB_HOST
      MYSQL_DATABASE: $DOCKER_MYSQL_DATABASE
      MYSQL_PORT: 3306
      MYSQL_USER: $DOCKER_MYSQL_USER
      MYSQL_PASSWORD: $DOCKER_MYSQL_PASSWORD
      S3_REGION: $DOCKER_S3_REGION
      S3_BUCKET: $DOCKER_S3_BUCKET
      S3_ACCESS_KEY_ID: $S3_ACCESS_KEY_ID
      S3_SECRET_ACCESS_KEY: $S3_SECRET_ACCESS_KEY
    container_name: momophoto_api
    restart: always
    command: sh start_api.sh
    networks:
      - default
